# This is a basic workflow to help you get started with Actions

name: publishdocs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cupcakearmy/confluence-markdown-sync@v1.0.1
        with:
          from: './README.md'
          to: '294913' # The confluence page id where to write the output
          cloud: '7dd34779-7c12-156d-kc2c-66j9kkk416c2'
          user: 'johnhurst@gmail.com'
          token: ${{ secrets.CONFLUENCE }}
